#pragma once
#include "CoreMinimal.h"
#include "EPPOSE_ID.generated.h"

UENUM(BlueprintType)
enum class EPPOSE_ID : uint8 {
    PPOSE_ID_00,
    PPOSE_ID_01,
    PPOSE_ID_02,
    PPOSE_ID_03,
    PPOSE_ID_04,
    PPOSE_ID_05,
    PPOSE_ID_06,
    PPOSE_ID_07,
    PPOSE_ID_08,
    PPOSE_ID_09,
    PPOSE_ID_10,
    PPOSE_ID_11,
    PPOSE_ID_12,
    PPOSE_ID_13,
    PPOSE_ID_14,
    PPOSE_ID_15,
    PPOSE_ID_16,
    PPOSE_ID_17,
    PPOSE_ID_18,
    PPOSE_ID_19,
    PPOSE_ID_20,
    PPOSE_ID_21,
    PPOSE_ID_22,
    PPOSE_ID_23,
    PPOSE_ID_24,
    PPOSE_ID_25,
    PPOSE_ID_26,
    PPOSE_ID_27,
    PPOSE_ID_28,
    PPOSE_ID_29,
    PPOSE_ID_30,
    PPOSE_ID_31,
    PPOSE_ID_32,
    PPOSE_ID_33,
    PPOSE_ID_34,
    PPOSE_ID_35,
    PPOSE_ID_36,
    PPOSE_ID_37,
    PPOSE_ID_38,
    PPOSE_ID_39,
    NUM,
};

